### ISSUE TITLE
List all methods

### ISSUE THREAD

**Issue by chunrong** [plum-umd/redexer#10]
Is there a command like "ruby scripts/cmd.rb target.(apk|dex) --cmd classes"? I need to list all methods written in the given apk.

Thanks for your great tools.

**Comment by kmicinski** [comment]
There is not a command in redexer itself which lists the classes:

`redexer -classes` should do it, along with `redexer -unparse`.

It looks like `cmd.rb` exports these options in the `--cmd classes` and
`--cmd unparse`.

`unparse` will give you fine grained information about the dex file: list
of methods, classes, code items, etc...  I'd suggest you simply do that and
manipulate the output via sed/awk.

Kris

**Comment by kmicinski** [comment]
I apologize, I realize my last email was confusing.

There *is* a command in redexer which lists the classes.

Accidentally put a "not" in there, apologies

Kris

**Comment by chunrong** [comment]
Thanks a lot and it does work. 'Classes' can also be from 'unparse'.
