### ISSUE TITLE
Redexer crashes during logging

### ISSUE THREAD

**Issue by eldr4d** [plum-umd/redexer#14]
After trying to log various applications, in some of them redexer produced the following error and crashed (the error was the same for all the apps):

Raised at file "list.ml", line 179, characters 16-25
Called from file "src/modify.ml", line 445, characters 9-41
Called from file "src/modify.ml", line 460, characters 18-43
Called from file "src/ext/logging.ml", line 426, characters 22-44
Called from file "src/visitor.ml", line 144, characters 4-17
Called from file "list.ml", line 73, characters 12-15
Called from file "ocamlutil/dynArray.ml", line 342, characters 2-18
Called from file "src/visitor.ml", line 191, characters 2-36
Called from file "ocamlutil/stats.ml", line 106, characters 10-15
Re-raised at file "ocamlutil/stats.ml", line 110, characters 7-8
Called from file "src/ext/logging.ml", line 625, characters 2-45
Called from file "ocamlutil/stats.ml", line 106, characters 10-15
Re-raised at file "ocamlutil/stats.ml", line 110, characters 7-8
Called from file "src/main.ml", line 202, characters 2-33
Re-raised at file "src/main.ml", line 180, characters 2-48
Called from file "src/main.ml", line 358, characters 8-13

**Comment by kmicinski** [comment]
The reason this error is happening is that Redexer attempts to add logging instrumentation to a method that contains this byte code sequence: 

    0x00376C04   | op: goto/32, opr [0x00376C04]

Or something like that.  In the app you sent me (Nikos), the method is `com/immersion/hapticmediasdk/models/HapticFileInformation/getFileLength`

I suspect that the other apps have a similar problem.

I am very surprised that this is valid byte code: I am booting up an emulator and installing the app now to see if it complains at me for this.

**Comment by kmicinski** [comment]
As a very hacky attempt at a solution, I have caught exceptions within the `Logging` module (specifically the code to visit code items).  [This commit](https://github.com/plum-umd/redexer/commit/95b5cd15e6dd795135dcf2be04e19143c0c8adad) simply throws away logging on methods that encounter errors.

**Comment by jsjeon** [comment]
One assumption behind get_last_cursor (the reported error point) was that methods in the dex file generated from `dx` will end with either `return-*` or `throw` bytecodes.  I'm very surprised, too, that this is no longer the case.

**Comment by kmicinski** [comment]
Closing this issue as we've decided its due to malformed byte code in the original app.
