### ISSUE TITLE
Make fail with can't find SHA library

### ISSUE THREAD

**Issue by fashioncj** [plum-umd/redexer#21]
I follow the readme.md but when i make i find those error:
---
ocamlbuild -cflag -dsource -use-ocamlfind main.native
\+ ocamlfind ocamldep -package sha,str,unix,ppx_deriving.std,ppx_deriving_yojson -modules src/main.ml > src/main.ml.depends
ocamlfind: Package `sha' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
make: *** [main.native]  error 10

---
$ opam list
\# Installed packages for system:
base-bigarray   base  Bigarray library distributed with the OCaml compiler
base-threads    base  Threads library distributed with the OCaml compiler
base-unix       base  Unix library distributed with the OCaml compiler
ocamlfind      1.5.6  A library manager for OCaml
sha              1.9  Binding to the SHA cryptographic functions

----
$ ocamlfind list
bigarray            (version: [distributed with Ocaml])
camlp4              (version: [distributed with Ocaml])
camlp4.exceptiontracer (version: [distributed with Ocaml])
camlp4.extend       (version: [distributed with Ocaml])
camlp4.foldgenerator (version: [distributed with Ocaml])
camlp4.fulllib      (version: [distributed with Ocaml])
camlp4.gramlib      (version: [distributed with Ocaml])
camlp4.lib          (version: [distributed with Ocaml])
camlp4.listcomprehension (version: [distributed with Ocaml])
camlp4.locationstripper (version: [distributed with Ocaml])
camlp4.macro        (version: [distributed with Ocaml])
camlp4.mapgenerator (version: [distributed with Ocaml])
camlp4.metagenerator (version: [distributed with Ocaml])
camlp4.profiler     (version: [distributed with Ocaml])
camlp4.quotations   (version: [distributed with Ocaml])
camlp4.quotations.o (version: [distributed with Ocaml])
camlp4.quotations.r (version: [distributed with Ocaml])
camlp4.tracer       (version: [distributed with Ocaml])
compiler-libs       (version: [distributed with Ocaml])
compiler-libs.bytecomp (version: [distributed with Ocaml])
compiler-libs.common (version: [distributed with Ocaml])
compiler-libs.optcomp (version: [distributed with Ocaml])
compiler-libs.toplevel (version: [distributed with Ocaml])
dynlink             (version: [distributed with Ocaml])
findlib             (version: 1.4)
graphics            (version: [distributed with Ocaml])
labltk              (version: [distributed with Ocaml])
num                 (version: [distributed with Ocaml])
num-top             (version: 1.4)
num.core            (version: [internal])
oasis               (version: 0.3.0)
oasis.base          (version: 0.3.0)
oasis.builtin-plugins (version: 0.3.0)
oasis.cli           (version: 0.3.0)
oasis.dynrun        (version: 0.3.0)
ocamlbuild          (version: [distributed with Ocaml])
odn                 (version: 0.0.11)
odn.with            (version: n/a)
odn.with.syntax     (version: 0.0.11)
odn.without         (version: n/a)
odn.without.syntax  (version: 0.0.11)
pcre                (version: 7.0.4)
plugin-loader       (version: 0.3.0)
stdlib              (version: [distributed with Ocaml])
str                 (version: [distributed with Ocaml])
threads             (version: [distributed with Ocaml])
threads.posix       (version: [internal])
threads.vm          (version: [internal])
type_conv           (version: 109.28.00)
unix                (version: [distributed with Ocaml])
userconf            (version: 0.3.0)

**Comment by kmicinski** [comment]
Do you have the ocamlsha library installed? This build error indicates it
is not being found

**Comment by fashioncj** [comment]
@kmicinski i fix it by reinstall ocaml though LUNCHPAD ppa and fix it.
Now this project also need:
opam install ppx_deriving
opam install ppx_deriving_yojson

by the way,when i use the '$ ruby scripts/cmd.rb target.apk --cmd directed',it always say '/home/fashioncj/redex/redexer/scripts/apk.rb:120:in `directed': wrong number of arguments (1 for 0) (ArgumentError)
	from scripts/cmd.rb:261:in `<main>'
', i use the apktool in tools files which version is 2.0.0

**Comment by kmicinski** [comment]
Thanks for following up.

I added documentation to the Redexer README to note that it now requires ppx_deriving and the deriving yojson extension.

The `directed` command is a bug. I'm not sure what the status of the directed execution framework is, since I didn't write that tool, but I'll assign myself to fix the scripts so you can at least try to use it.

**Comment by fashioncj** [comment]
i run ruby version is 1.9.3, is the ruby version error?

**Comment by kmicinski** [comment]
No, it was just a naive bug in the scripts that I messed up at one point when I added some extra functionality.

Commit 027f93d fixes this issue.

**Comment by fashioncj** [comment]
@kmicinski I merge the code, and success run it. Thanks

**Comment by fashioncj** [comment]
@kmicinski i find the output is different from the paper of brahmastra. is 'directed' complate the static part of the brahmastra?

**Comment by kmicinski** [comment]
That question I cannot answer, as I was not an author of that paper, nor did I write the code. @jsjeon was, however.

**Comment by jsjeon** [comment]
@fashioncj Could you open a new, separate issue for that, along with more detailed explanations?

**Comment by fashioncj** [comment]
@jsjeon Ok.
