### ISSUE TITLE
the discuss of 'directed exploration'

### ISSUE THREAD

**Issue by fashioncj** [plum-umd/redexer#22]
I find 2 questions,
+ How to the call graph of the direct method? It seems different from the paper of Figure 5.

>THE LOG I FETCH IS:

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$10;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$11;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$1;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$2;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$3;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$4;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$5;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$6;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$7;

            Lcom/huanxiao/store/ui/LoginActivity;->onCreate(Landroid/os/Bundle;)V
      -##-> Lcom/huanxiao/store/ui/LoginActivity$8;

+ The repackage APK files seem is no different from the original APK files. This function whether help us to add some necessary invoke like the paper say and what's the different of the AndroidManifest.xml and dex file in result file?

**Comment by jsjeon** [comment]
Two inputs to `directed` command are: 1) the target app and 2) APIs of interest.  As mentioned in README, see `data/directed.txt` to see how to set up APIs you wan to direct your app.  The main reason you saw the different call paths is that you inputed a different app.  According to your log, your app's package name should be: `com.huanxiao.store` or something that begins with that.  The running example we used in Figure 5 is: `ch.smalltech.battery.free`.  Needless to say, different apps have different structures, hence different call paths to certain API invocations.

Technically, `redexer` can do the whole process described in the Brahmastra paper, but, when I joined that project, the dynamic rewriting part was already done by using another toolset.  (And only static analysis part has been implemented inside `redexer`.)  Thus, the output of `directed` commandis just call paths towards APIs of interest, not rewritten, repackaged apps that are self-executable (as explained in the paper).

**Comment by fashioncj** [comment]
@jsjeon Thanks for you explain. If i want to modify some function of directed,which files should i focus?

**Comment by kmicinski** [comment]
Looks like the implementation of that code is in `src/ext/directed.ml`. It uses the configuration file Jinseong pointed out, `data/directed.txt`.

**Comment by fashioncj** [comment]
@jsjeon I‘m interesting in 'self-executable'. And I want to redo it. Can you give me some tips about 'what's the smali code should be added in 'OnCreate()' or other to call the some virtual methods such as 'OnClick()' ?'.(introduction in section 3 of the paper 'self-execution of app' )

**Comment by jsjeon** [comment]
I'm not that familiar with Soot/Dexpler/Smali, and I don't think I can access to the source code of that part. So, I'm not 100% sure about its details.  It would be better for you to contact the first author; you can find his email at his website: http://ravi.bhoraskar.com/

At a very high level, the key idea is to instrument an instruction that calls registered handlers.  E.g., for Figure 3 in the paper, the code after instrumentation would look like:
```java
ImageButton b = (ImageButton) findViewById(R.id.b1);
b.setOnClickListener(new OnClickListener() {
  public void onClick(View v) { ... }});
... // after it is guaranteed that all UIs are loaded properly
b.performClick(); // <- instrumented
```

Another key idea is, if there are any ambiguity, e.g., which widgets are associated with which handlers, we can generate all possible rewritten apps each of which calls one of those candidates.  Say, there is a button whose handlers might be a, b, or c, for any reason.  Then, we can generate three different rewritten apps that try all those possibilities.

**Comment by fashioncj** [comment]
I try to send a emali to Ravi but no response until now.
Can you give me some tips at 

`invoke-virtual {p0, v1}, Lme/chenjia/onclicktest/MainActivity$1;->onClick(Landroid/view/View;)V`

where should i add in the function OnCreate() and what's the param, fill with p0,v0 or v1?

**Comment by jsjeon** [comment]
I think you built a bogus, example app that attempted to call a handler programmatically, and then saw how its smali code looks like?  If so, you already knew what values p0, v0, or v1 are filled with, by stepping backward until the method entry.

If I remember correctly, in smali's method call convention, registers started with prefix `p` are parameters, and registers started with prefix `v` are local variables.  According to `onClick`'s signature, it receives `this` pointer, an instance of a handler (in this case, an instance of anonymous class `MainActivity$1`), as well as source `View`.  I guess `p0` would be `this` pointer of the current method, `onCreate`, then it means your main class, `MainActivity` `implements` an interface for handler (am I correct?).  Anyhow,  `p0` would be `this` pointer, and `v1` would refer to the instance where this event happens.

**Comment by ravibhoraskar** [comment]
Hi @fashioncj! I would recommend not trying to manipulate the smali code directly, but instead use soot, and then manipulate the jimple format. http://www.bodden.de/2013/01/08/soot-android-instrumentation/ has an example of how you can add a print statement to a function — you can use similar code to insert the 'performClick' method on the listener. 

I think you will have a much easier time with this — dalvik has a weird addressing system, which makes manipulating it directly really hard.
