### ISSUE TITLE
basic apk logging issue

### ISSUE THREAD

**Issue by vherzog** [plum-umd/redexer#28]
Hello! 

I am currently trying to use Redexer to implement logging to an apk when certain methods are called (like the tutorial). However, I am having a few issues.

When I run
     ruby scripts/cmd.rb my-app-base.apk --cmd logging

It seems to run correctly, as this is the terminal output:

java -jar /home/vherzog/redexer/scripts/../tools/apktool.jar d -f --no-src --keep-broken-res -o tmp_dir_th870pye ../my-app-base.apk
/home/vherzog/redexer/scripts/../redexer  -out tmp_dir_th870pye/classes.dex tmp_dir_th870pye/classes.dex -logging  
====== redexer performance statistics ======
TOTAL                          20.116 s
  parse                           0.660 s
  merge                           0.468 s
  logging                        16.144 s
    transition                      3.964 s
      cfg                             0.000 s
      pdom                            0.000 s
    instrument                      5.740 s
      cfg                             0.004 s
      pdom                            0.000 s
    expand-opr                      0.344 s
      reach                           0.316 s
        cfg                             0.032 s
        trans                           0.008 s
        meet                            0.020 s
  rename                          0.000 s
  dump                            2.844 s
    place                           1.088 s
    calc.                           0.328 s
    trans                           1.400 s
Timing used
Memory statistics: total=7474.59MB, max=432.41MB, minor=3663.91MB, major=4407.82MB, promoted=597.14MB
    minor collections=3374  major collections=78 compactions=1
java -jar /home/vherzog/redexer/scripts/../tools/apktool.jar b -f -o tmp_dir_th870pye/unsigned.apk tmp_dir_th870pye
...
.# of method  logging instruction(s): 268
.# of API-use logging instruction(s): 170
.# of operand expand(s): 810
java -jar /home/vherzog/redexer/scripts/../tools/apktool.jar b -f -o tmp_dir_th870pye/unsigned.apk tmp_dir_th870pye
I: Using Apktool 2.2.0
I: Copying tmp_dir_th870pye classes.dex file...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
java -jar /home/vherzog/redexer/scripts/../tools/signapk.jar /home/vherzog/redexer/scripts/../tools/platform.x509.pem /home/vherzog/redexer/scripts/../tools/platform.pk8 tmp_dir_th870pye/unsigned.apk tmp_dir_th870pye/unaligned.apk
zipalign 4 tmp_dir_th870pye/unaligned.apk base.apk

However, when I unpack the new apk file, there are no changes from the old one (no logging implemented).

Is there another command I should be running in order to properly use this element of redexer?

Thanks!

**Comment by kmicinski** [comment]
Hi Veronica,

Sorry for being delinquent on this matter. I want to work on solving this this week. Is this still something you see? I've been busy working on job applications so maintenance on redexer has slipped. My apologies for not responding sooner.

Kris

**Comment by vherzog** [comment]
Hi Kris,

Not a problem at all! It seems that my errors have been fixed.

I re-cloned redexer and ran makefile again and it seems to be running fine!

Thanks for your response.

Best,
Veronica

**Comment by kmicinski** [comment]
Hi Veronica,

Thanks for letting me know. I am actively working on Redexer's logging code at the moment, because I'm using it for another research related project. This is to say that I have this code checked in mentally, and I'm probably more able to comment on it now.

Kris

**Comment by vherzog** [comment]
Not a problem. Since I am working on something similar, would you mind if I
asked you a quick question regarding redexer's logging capabilities?

When calling the logging command on an apk, does redexer add logging for
all methods in the apk? Or only a certain list of them? I am looking to log
any method called in any given apk.

Thanks for you help!

Best,
Veronica
