### ISSUE TITLE
Extract the disassemly and DEX parsers into separate opam packages

### ISSUE THREAD

**Issue by XVilka** [plum-umd/redexer#33]
It would be nice to be able to reuse the code in other projects.

**Comment by kmicinski** [comment]
This is a nice idea, though I've currently taken a faculty position and can no longer commit to major feature requests such as this on Redexer. I am of course happy to help others if they would like to pursue this. Would you be interested in doing so?

**Comment by XVilka** [comment]
I have a question. I want to use parts of this library under MIT license - the project is open source. Is this possible? Currently BSD-3 only prevents this because of incompatibilities: https://softwareengineering.stackexchange.com/questions/121998/mit-vs-bsd-vs-dual-license

**Comment by kmicinski** [comment]
Hm.. That's a good question. I did not originally write the dex manipulation code, so I don't feel comfortable arbitrarily changing the license. @jsjeon: you wrote this code and chose the license, what are your feelings on this?

I could pull out these files and put them into a separate library, but I don't think that would solve your problem, since I believe that would mean the license would be preserved.

**Comment by XVilka** [comment]
Also `dex.ml[i]` parsing code, while we are on it.

**Comment by jsjeon** [comment]
I'm glad I didn't choose GPL. :)

So, IIUC, the only difference between BSD and MIT licenses is to distribute without contribution credits? As long as you save the links and original copyrights (as you mentioned), I think it's okay. Plus, BAP is already open-sourced, so there won't be a subtle case like redistributing it after adding new contributions but not open-sourcing it.

**Comment by XVilka** [comment]
@jsjeon of course I am. I will also paste the link to this repository in the header of used files, so don't worry.

**Comment by kmicinski** [comment]
@XVilka does this give you what you ned to know? Do we need to do anything else to help you out? I don't mean to sound as if I'm not eager to help, just can't commit to more than a few hours of hacking and don't want to overpromise. I'm definitely eager to provide high-level advice or answer precise questions.

**Comment by XVilka** [comment]
@kmicinski sure, code is easy enough to understand. I will post a link here once it's pushed or merged, just for your information.
